config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'homes/about' => 'homes#about', as: 'about'

  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'search' => 'users#search', as: 'users_search'
  get 'search' => 'post_images#search', as: 'post_images_search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :comment, presence: true, length: {maximum: 150}
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :shop_name, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, word)
    if search == 'perfect_match'
      @post_image = PostImage.where('shop_name LIKE?', "#{word}")
    elsif search == 'forward_match'
      @post_image = PostImage.where('shop_name LIKE?', "#{word}%")
    elsif search == 'backword_match'
      @post_image = PostImage.where('shop_name LIKE?', "%#{word}")
    elsif search == 'partial_match'
      @post_image = PostImage.where('shop_name LIKE?', "%#{word}%")
    else
      @post_image = PostImage.all
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  
  has_many :followings, through: :relationships, source: :follower
  has_many :followers, through: :reverse_of_relationships, source: :following

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def follow(user_id)
    relationships.create(follower_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(follower_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == 'perfect_match'
      @user = User.where('name LIKE?', "#{word}")
    elsif search == 'forward_match'
      @user = User.where('name LIKE?', "#{word}%")
    elsif search == 'backword_match'
      @user = User.where('name LIKE?', "%#{word}")
    elsif search == 'partial_match'
      @user = User.where('name LIKE?', "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: @post_image.id)
    favorite.post_image_id = @post_image.id
    favorite.save
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.post_image_id = @post_image.id
    unless @post_comment.save
      render 'error'
    end
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    @post_comment = current_user.post_comments.find_by(post_image_id: @post_image.id)
    @post_comment.destroy
  end

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_image_path(@post_image.id)
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end
  
  def search
    @post_images = PostImage.looks(params[:search], params[:word])
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def destroy
    current_user.unfollow(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/seaches_controller.rb
class SeachesController < ApplicationController
def search
  @range = params[:range]
  @word = params[:word]
  if @range == 'User'
    @users = User.looks(params[:search], params[:word])
  else
    @post_images = PostImage.looks(params[:search], params[:word])

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def search
    @word = params[:word]
    @users = User.looks(params[:search], params[:word])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/seaches_helper.rb
module SeachesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if post_image.favorited_by?(current_user) %>
  <p>
    <%= link_to post_image_favorites_path(post_image), remote: true, method: :delete do %>
      ❤<%= post_image.favorites.count %>いいね
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to post_image_favorites_path(post_image), remote: true, method: :post do %>
      ♡<%= post_image.favorites.count %>いいね
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$("#favorite<%= @post_image.id %>").html("<%= j(render 'favorites/favorite-btn', post_image: @post_image) %>");

app/views/favorites/destroy.js.erb
$("#favorite<%= @post_image.id %>").html("<%= j(render 'favorites/favorite-btn', post_image: @post_image) %>");

app/views/homes/about.html.erb
<h1>about</h1>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/post_comments/_count.html.erb
コメント件数: <%= post_image.post_comments.count %>

app/views/post_comments/_form.html.erb
<%= form_with model: [post_image, post_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/post_comments/_index.html.erb
<% post_image.post_comments.each do |post_comment| %>
  <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %> <%= post_comment.comment %>
  <% if post_comment.user == current_user %>
    <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, remote: true %>
  <% end %>
<% end %>

app/views/post_comments/create.js.erb
$("#count<%= @post_image.id %>").html("<%= j(render "post_comments/count", post_image: @post_image) %>");
$("#index<%= @post_image.id %>").html("<%= j(render "post_comments/index", post_image: @post_image) %>");
$("#post_comment_comment").val('');

app/views/post_comments/destroy.js.erb
$("#count<%= @post_image.id %>").html("<%= j(render "post_comments/count", post_image: @post_image) %>");
$("#index<%= @post_image.id %>").html("<%= j(render "post_comments/index", post_image: @post_image) %>");

app/views/post_comments/error.js.erb
$("#comments_error").html("<%= j(render 'layouts/errors', post_comment: @post_comment) %>");

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<%= render "list", post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_image do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image, size: "500x500"%>
  <p>ショップ名: <%= @post_image.shop_name %></p>
  <p>説明: <%= @post_image.caption %></p>
  <p>投稿ユーザー画像: <%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム: <%= @post_image.user.name %></p>
  <p>投稿日: <%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
<div id="favorite<%= @post_image.id %>">
  <%= render "favorites/favorite-btn", post_image: @post_image %>
</div>

<div>
  <p id="count<%= @post_image.id %>">
    <%= render "post_comments/count", post_image: @post_image %>
  </p>
  <div id="index<%= @post_image.id %>">
    <%= render "post_comments/index", post_image: @post_image %>
  </div>
</div>
<div id="comments_error">
  <%= render "layouts/errors", post_comment: @post_comment %>
</div>
<div id="form<%= @post_image.id %>">
  <%= render "post_comments/form", post_image: @post_image, post_comment: @post_comment %>
</div>

app/views/relationships/_follow-btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to 'フォロー解除', user_relationships_path(user.id), class: "btn btn-danger",  remote: true, method: :delete %>
<% else %>
  <%= link_to 'フォローする', user_relationships_path(user.id), class: "btn btn-success", remote: true, method: :post %>
<% end %>

app/views/relationships/_followers.html.erb
<%= user.followers.count %>

app/views/relationships/_followings.html.erb
<%= user.followings.count %>

app/views/relationships/create.js.erb
$("#<%= @user.id %>follow").html("<%= j(render "relationships/follow-btn", user: @user ) %>");
$("#<%= current_user.id %>followings-count").html("<%= j(render "relationships/followings", user: current_user) %>");
$("#<%= @user.id %>followers-count").html("<%= j(render "relationships/followers", user: @user) %>");

app/views/relationships/destroy.js.erb
$("#<%= @user.id %>follow").html("<%= j(render "relationships/follow-btn", user: @user ) %>");
$("#<%= current_user.id %>followings-count").html("<%= j(render "relationships/followings", user: current_user) %>");
$("#<%= @user.id %>followers-count").html("<%= j(render "relationships/followers", user: @user) %>");

app/views/relationships/followers.html.erb
<div class="container">
  <h2>フォロワー</h2>
  <table class = "table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th>フォロー数</th>
        <th>フォロワー数</th>
        <th colspan="6"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(100,100) %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td>
          <% if user.id != current_user.id %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー解除', user_relationships_path(user.id), class: "btn btn-danger", method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), class: "btn btn-success", method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id), class: "btn btn-info" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  

app/views/relationships/followings.html.erb
<div class="container">
  <h2>フォロー</h2>
  <table class = "table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th>フォロー数</th>
        <th>フォロワー数</th>
        <th colspan="6"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(100,100) %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td>
          <% if user.id != current_user.id %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー解除', user_relationships_path(user.id), class: "btn btn-danger", method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), class: "btn btn-success", method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id), class: "btn btn-info" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  

app/views/seaches/_search.html.erb
<div class="search_form">
  <%= form_with url: search_path, local: true, class: "center-block", method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['User'], ['Book']]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "ProfileImage" %>
  <%= f.file_field :profile_image, accept: "image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="search_form">
      <%= form_with url: post_images_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
      <table class = "table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th>フォロー数</th>
            <th>フォロワー数</th>
            <th colspan="5"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user.id) do %>
                <%= image_tag user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td id="<%= current_user.id %>followings-count">
              <%= render "relationships/followings", user: user %>
            </td>
            <td id="<%= user.id %>followers-count">
              <%= render "relationships/followers", user: user %>
            </td>
            <td id="<%= user.id %>follow">
              <% if user.id != current_user.id %>
                <%= render "relationships/follow-btn", user: user %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h4><%= @user.name %></h4>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>フォロー数</th>
          <th>
            <%= link_to user_followings_path(@user.id) do %>
              <%= @user.followings.count %>
            <% end %>
          </th>
        </tr>
        <tr>
          <th>フォロワー数</th>
          <th>
            <%= link_to user_followers_path(@user.id) do %>
              <%= @user.followers.count %>
            <% end %>
          </th>
        </tr>
      </table>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "post_images/list", post_images: @post_images %>
    </div>
  </div>
</div>